catalog_name: maven_training_databricks
schema_name: default-ccc
experiment_name_basic: /Shared/default-ccc-basic
experiment_name_custom: /Shared/default-ccc-custom
experiment_name_fe: /Shared/default-ccc-fe

# parameters:
#   learning_rate:0.01
#   n_estimators:1000
#   max_depth:6

num_features:
  - SEX
  - EDUCATION
  - MARRIAGE
  - PAY_0
  - PAY_2
  - PAY_3
  - PAY_4
  - PAY_5
  - PAY_6

cat_features:
  - LIMIT_BAL
  - AGE
  - BILL_AMT1
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6

target: default payment next month